---
# tasks file for frontend
- name: Installing Software
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "@nodejs:14"
    - git
    - firewalld
  tags:
      - application
- name: Pulling code 
  become: true
  become_user: "{{ frontend_user }}"
  ansible.builtin.git:
    repo: 'https://github.com/bezkoder/react-crud-web-api.git'
    dest: "{{ frontend_path }}"
    force: yes
  tags:
      - application
- name: Copy files
  become: true
  template:
    src: http-common.js
    dest: "{{ frontend_path }}/src"
  tags:
      - application
- name: Installing dependencies
  become: true
  become_user: "{{ frontend_user }}"
  community.general.npm:
    path: "{{ frontend_path }}"
  tags:
      - application

- name: Building the frontend application
  become: true
  become_user: "{{ frontend_user }}"
  ansible.builtin.shell: npm run-script build
  args:
    chdir: "{{ frontend_path }}"
  tags:
      - application