---
- hosts: localhost
  tasks:
    - name: "include aws role"
      import_role:
        name: aws
- hosts: aws_ec2
  vars:
    frontend_user: frontend
    frontend_path: /frontend
  tasks:
    - name: ping
      ping:
      tags:
      - provision
    - name: Create the frontend user user
      become: true
      ansible.builtin.user:
        name: "{{ frontend_user }}"
      tags:
        - application

    - name: Create the {{ frontend_path }} folder
      become: true
      ansible.builtin.file:
        path: "{{ frontend_path }}"
        state: directory
        mode: '0755'
        owner: "{{ frontend_user }}"
      tags:
      - application

    - name: Include role frontend
      vars:
        frontend_user: frontend
        api_location: /api
      include_role:
        name: frontend
      tags:
      - application

    - name: Include role nginx
      vars:
        http_static_dir: /frontend/build
        backend_url: http://localhost:8080
      include_role:
        name: nginx
      tags:
      - application

    - name: Include role database
      vars:
        backend_db_password: password
        open_firewall: yes
      include_role:
        name: database
      tags:
      - application

    - name: Include role backend
      vars:
        backend_db_password: password
        backend_db_host: "localhost"
      include_role:
        name: backend
      tags:
      - application
